//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikroTikFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MikroTikFinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /interface pppoe-client add user=&quot;$1&quot; password=&quot;$2&quot; add-default-route=yes disabled=no interface=wlan1
        ////system identity set name=&quot;edited from outside&quot;
        ////ip dns static add name=primary-dns address=87.250.97.250
        ////ip dns static add name=secondary-dns address=87.250.98.250
        ////ip pool add name=pool1 ranges=192.168.88.1-192.168.88.254
        ////ip dhcp-server add name=dhcp_server interface=ether1 lease-time=3d address-pool=pool1 disabled=no
        ////ip dhcp-server network add address=192.168.88.0/24 gateway=192.168.88.1 dns-ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ip address add address=192.168.88.1/24 interface=ether1
        ////ip accounting set enabled=no
        ////ip dns set allow-remote-requests=no
        ////ip neighbor discovery set [find] discover=yes
        ////system ntp client set enabled=yes mode=unicast primary-ntp=91.191.19.21
        ////interface wireless set 0 country=ireland band=5ghz-a/n wireless-protocol=any
        ////interface wireless set 0 ht-txchains=0,1 ht-rxchains=0,1 disabled=no channel-width=20mhz frequency-mode=superchannel
        ////interface wireless set 0 scan-list=5180,5200,5220,5240,5260,5280 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_sxt {
            get {
                return ResourceManager.GetString("script_sxt", resourceCulture);
            }
        }
    }
}
